github action: redo better

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,6 +2,16 @@
 # Use of this source code is governed under the Apache License, Version 2.0
 # that can be found in the LICENSE file.
 
+# References:
+# https://github.com/actions/checkout
+# https://github.com/actions/setup-go
+# https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow
+# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions/
+# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
+# https://docs.github.com/en/rest/commits/comments#create-a-commit-comment
+# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
+# https://docs.github.com/en/actions/learn-github-actions/contexts
+
 on: [push, pull_request]
 name: Run tests
 jobs:
@@ -22,7 +32,6 @@ jobs:
         # Do not forget to bump every 6 months!
         gover: ["1.21"]
     env:
-      CGO_ENABLED: 0
       PYTHONDONTWRITEBYTECODE: x
     steps:
     - name: Turn off git core.autocrlf
@@ -34,43 +43,80 @@ jobs:
     - uses: actions/setup-go@v4
       with:
         go-version: "~${{matrix.gover}}.0"
+    - name: 'go install necessary tools'
+      if: always()
+      run: |
+        go install github.com/maruel/pat/cmd/ba@latest
     - name: 'Check: go test -cover'
       if: always()
-      run: go test -timeout=5m -covermode=count -coverprofile coverage.txt -bench=. -benchtime=1x ./...
+      run: go test -timeout=120s -covermode=count -coverprofile coverage.txt -bench=. -benchtime=1x ./...
       # Don't send code coverage if anything failed to reduce spam.
     - uses: codecov/codecov-action@v3
     - name: 'Cleanup'
       if: always()
       run: rm coverage.txt
     - name: 'Check: go test -race'
-      run: go test -timeout=5m -race -bench=. -benchtime=1x ./...
-      env:
-        CGO_ENABLED: 1
-    - name: 'Install'
-      if: always()
-      run: go install .
-    - name: "Check: go generate doesn't modify files"
+      run: go test -timeout=120s -race -bench=. -benchtime=1x ./...
+    - name: 'Check: benchmark 📈'
+      run: ba -against HEAD~1
+    - name: "Check: tree is clean"
       if: always()
       run: |
-        go generate ./...
-        # Also test for untracked files. go generate should not generate ignored
-        # files either.
+        # Nothing should have changed in the tree up to that point and no
+        # unsuspected file was created.
         TOUCHED=$(git status --porcelain --ignored)
         if ! test -z "$TOUCHED"; then
-          echo "go generate created these files, please fix:"
+          echo "Oops, something touched these files, please cleanup:"
           echo "$TOUCHED"
-          false
-        fi
-    - name: "Check: go mod tidy doesn't modify files"
-      if: always()
-      run: |
-        go mod tidy
-        TOUCHED=$(git status --porcelain --ignored)
-        if ! test -z "$TOUCHED"; then
-          echo "go mod tidy was not clean, please update:"
           git diff
           false
         fi
+
+
+    # Run linters. This workflow can be merged with the test_all one if desired
+    # to cut on runtime, at the cost of latency. I dislike waiting for results
+    # so I prefer to run them in parallel.
+  lint:
+    name: "lint: go${{matrix.gover}}.x/${{matrix.os}}"
+    runs-on: "${{matrix.os}}"
+    continue-on-error: true
+    defaults:
+      run:
+        shell: bash
+    strategy:
+      fail-fast: false
+      matrix:
+        # You may want to run only on linux to save on cost. Projects with
+        # OS-specific code benefits from explicitly linting on macOS and
+        # Windows.
+        os: [ubuntu-latest, macos-latest, windows-latest]
+        # Do not forget to bump every 6 months!
+        gover: ["1.21"]
+    env:
+      PYTHONDONTWRITEBYTECODE: x
+    steps:
+    - name: Turn off git core.autocrlf
+      if: matrix.os == 'windows-latest'
+      run: git config --global core.autocrlf false
+    - uses: actions/checkout@v3
+    - uses: actions/setup-go@v4
+      with:
+        go-version: "~${{matrix.gover}}.0"
+    - name: "Debug"
+      run: |
+        echo HOME = $HOME
+        echo GITHUB_WORKSPACE = $GITHUB_WORKSPACE
+        echo PATH = $PATH
+        echo ""
+        echo $ ls -l $HOME/go/bin
+        ls -la $HOME/go/bin
+    - name: 'go install necessary tools'
+      if: always()
+      run: |
+        go install github.com/gordonklaus/ineffassign@latest
+        go install github.com/securego/gosec/v2/cmd/gosec@latest
+        go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
+        go install honnef.co/go/tools/cmd/staticcheck@latest
     - name: 'go install necessary tools (ubuntu)'
       if: always() && matrix.os == 'ubuntu-latest'
       run: |
@@ -79,24 +125,56 @@ jobs:
     - name: 'Check: go vet'
       if: always()
       run: go vet -unsafeptr=false ./...
+    - name: 'Check: go vet shadow; shadowed variables'
+      if: always()
+      run: |
+        SHADOW_TOOL="$(which shadow)"
+        if [ -f "${SHADOW_TOOL}.exe" ]; then
+          SHADOW_TOOL="${SHADOW_TOOL}.exe"
+        fi
+        go vet -vettool=$SHADOW_TOOL ./...
+    - name: 'Check: inefficient variable assignment'
+      if: always()
+      run: ineffassign ./...
+    - name: 'Check: staticcheck'
+      if: always()
+      run: staticcheck ./...
+    - name: 'Check: gosec'
+      if: always()
+      run: gosec -fmt=golint -quiet ./...
+      # The following checks are not dependent on the OS or go build tags. Only
       # run them on ubuntu-latest since it's the fastest one.
     - name: 'Check: no executable was committed (ubuntu)'
       if: always() && matrix.os == 'ubuntu-latest'
       run: |
-        if find . -path '*.sh' -prune -o \
-            -path ./.git -prune -o \
-            -path './internal/sandbox/nsjail-linux-*' -prune -o \
-            -type f -executable -print | grep -e . ; then
+        if find . -path '*.sh' -prune -o -path ./.git -prune -o -type f -executable -print | grep -e . ; then
           echo 'Do not commit executables beside shell scripts'
           false
         fi
     - name: 'Check: addlicense; all sources have a license header (ubuntu)'
       if: always() && matrix.os == 'ubuntu-latest'
-      run: addlicense -check -ignore 'vendor/**' .
+      run: addlicense -check .
+    - name: 'Check: gofmt; code is well formatted (ubuntu)'
+      if: always() && matrix.os == 'ubuntu-latest'
+      run: |
+        FILES=$(gofmt -s -l .)
+        if ! test -z "$FILES"; then
+          echo 'Please run `gofmt -s -w` on the following files:' >> _gofmt.txt
+          echo "" >> _gofmt.txt
+          for FILE in ${FILES}; do
+            echo "- ${FILE}" >> _gofmt.txt
+          done
+          cat _gofmt.txt
+          echo "## ⚠ gofmt Failed" >> ../_comments.txt
+          echo "" >> ../_comments.txt
+          cat _gofmt.txt >> ../_comments.txt
+          echo "" >> ../_comments.txt
+          false
+        fi
     - name: "Check: misspelling; code doesn't contain misspelling (ubuntu)"
       if: always() && matrix.os == 'ubuntu-latest'
       run: |
-        ERR=$(find . -type f | grep -v vendor/ | xargs misspell)
+        ERR=$(misspell .)
         if ! test -z "$ERR"; then
           echo "$ERR"
           echo "## ⚠ misspell Failed" >> ../_comments.txt
@@ -120,6 +198,28 @@ jobs:
             --data "$(cat ../_comments.txt | jq -R --slurp '{body: .}')" \
             "${URL}" > /dev/null
           rm ../_comments.txt
+        fi
+    - name: "Check: go generate doesn't modify files"
+      if: always()
+      run: |
+        go generate ./...
+        # Also test for untracked files. go generate should not generate ignored
+        # files either.
+        TOUCHED=$(git status --porcelain --ignored)
+        if ! test -z "$TOUCHED"; then
+          echo "go generate created these files, please fix:"
+          echo "$TOUCHED"
+          false
+        fi
+    - name: "Check: go mod tidy doesn't modify files"
+      if: always()
+      run: |
+        go mod tidy
+        TOUCHED=$(git status --porcelain --ignored)
+        if ! test -z "$TOUCHED"; then
+          echo "go mod tidy was not clean, please update:"
+          git diff
+          false
         fi
 
 
